### ISSUE TITLE
Side Navigation Scroll Bar

### ISSUE THREAD

**Issue by bherendeen** [CodyHouse/cd-plutone-changelog#1]

**Comment by sebastiano-guerriero** [comment]
hi, do you have a screencast or a screenshot I can look at?

**Comment by bherendeen** [comment]
You can close this issue. I thought there was an error but it ended up being a VS Code error when displaying a preview. You guys do amazing work! I'm a happy pro customer.

**Comment by sebastiano-guerriero** [comment]
Thanks! 😊
