### ISSUE TITLE
M1 ARM node-sass Error

### ISSUE THREAD

**Issue by makebasic** [CodyHouse/cd-plutone-changelog#2]
1. I can run `npm install` only with `--ignore-scripts`
I found (https://github.com/sass/node-sass/issues/2877)

2. But if I want to run `npm run gulp watch` it says:
`Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (102)`
I found (https://github.com/sass/node-sass/issues/3033) and (https://sebastix.nl/blog/issue-with-node-sass-in-docker-on-apples-silicon-arm-m1-chipset/)

It would be nice if you can compile with sass instead of node-sass :)

Everything runs fine on my Mac (2010) with High Sierra...

**Comment by claudia-romano** [comment]
Hi there, sorry about that. You may need to upgrade the version of gulp-sass (from v4 to v5). This will fix your issue (gulp-sass v5 does not include nose-sass). 

Let me know if you need any help for that. Cheers!

**Comment by makebasic** [comment]
Thank you very much!
